config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#home'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'static_pages#contact'
  get '/info',            to: 'static_pages#info'
  get '/booking',         to: 'static_pages#booking'
  get '/trip1',           to: 'static_pages#trip1'
  get '/trip2',           to: 'static_pages#trip2'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :detect_device_variant
  
  
  private
    
  def detect_device_variant
    request.variant = :phone if browser.device.mobile?
    request.variant = :phone if browser.device.tablet?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
    def home
    end
    
    def about
    end
    
    def contact
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Returns title of page
    def full_title(page_title = '')
        base_title = "Skyline Journey"
        if page_title.empty?
            base_title
        else
            base_title + " | " + page_title
        end
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_application_layout.html.erb
<body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <% #debug(params) if Rails.env.development? %>
    </div>
</body>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-static-bottom">
</footer>

app/views/layouts/_header.html.erb
<div class="topnav" id="myTopnav">
<div class="center">
    <a href="/">Home</a>
    <a href="/about">About</a>
    <div class="dropdown">
      <a href="#" class="dropbtn">Trips</a>
        <div class="dropdown-content">
          <a href="/trip1">Tokyo Springtime 2019</a>
          <a href="/trip2">Tokyo August 2019</a>
        </div>
    </div>
    <a href="/info">I'm interested, what's next?</a>
    <a href="booking">Book your trip!</a> 
    <a href="/contact">Contact us!</a>
    
    
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class=" fa fa-2x fa-bars"></i>
  </a>
  </div>
</div>

app/views/layouts/_phone_header.html.erb
<span class="mobile-menu" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>


<div id="myNav" class="overlay">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <div class="overlay-content">
        
        <div class="container" id="logo">Test</div>
        <div class="container" id="logo-two">test</div>
    <br>
    <div class="container-center">
        <nav>
            <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path, id: "logo-three" %></li>
                <li><%= link_to "About", about_path, id: "logo-three" %></li>
                <li><%= link_to "Contact", contact_path, id: "logo-three" %></li>
            </ul>
        </nav>
    </div>
  </div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <%= display_meta_tags site: 'Skyline Journey' %>
  <meta property="og:url"           content="https://www.skylinejourney.com/" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Skyline Journey" />
  <meta property="og:description"   content="Small Group Tours" />
  <meta property="og:image"         content="assets/frontlogo.jpg" />
  <meta property="og:image" content="#{image_url('frontlogo.jpg')}" />
  
<meta name="viewport" content="width=device-width, initial-scale=1">
  <head>
    <title><%= full_title(yield(:title)) %></title>
      
      <%= favicon_link_tag 'favicon-32x32.png' %>
      
      
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      <%= render 'layouts/header' %>
  </head>
    <body>
    <%= render 'layouts/application_layout' %>
</body>

</html>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html+phone.erb
<% provide(:title, "About") %>
<div class="body-padding"></div>
<div class="mobile-padding">
    
<div class="row home-padding">
    <div class="center">
        <h1 class="logo">Skyline Journey</h1>
    </div>
</div>

<p>
</p>
    

<div class="row home-padding">
    
        <div class="about-main height-image"></div>
          

<div class="home-padding"></div>
Meet Marjorie & Ellen 😊 They have known each other for almost 10 years, and first traveled abroad together in 2017. 

Marjorie is an extremely experienced world traveler. She has been to Tokyo alone 15 times! She spends a full month there biannually for work. She has brought various friends and family along to Asia, to act as a tour guide & reveal to them the wonders of Japan. 

Ellen & Marjorie spent two weeks in Japan together in 2017. Ellen got to explore Tokyo and Mt. Fuji for the first time, and it was all totally stress-free because of Marjorie’s knowledge & guidance.

Ellen & Marjorie recently realized that together, they could make their dream job happen. Combining Marjorie's extensive experience in Japan & Ellen's work as a travel agent, they decided to launch Skyline Journey.
 
Skyline Journey is a US-based tour company. Marjorie & Ellen are the guides for small group tours, capped at around 20 people. Their goal is to give you a warm, welcoming, personalized, and authentic experience to the best of their ability.
</div>


<div class="row home-padding">
    
        <div class="about-1 height-image"></div>
        <a href="http://www.marjorieorourke.com/"><h2 class="logo">Click here to learn more about me!</h2></a>    

<div class="home-padding"></div>
Hi! I'm Marjorie O'Rourke, co-founder of Skyline Journey. We are a premiere American-based company, specializing in personalized, exclusive, worldwide travel.

I absolutely love to travel. I love waking up in a new location and seeing the amazing adventure before me. I'm also a foodie, so I really enjoy epicurean delights from all over this world.

My wanderlust began when I was a a teen, and has taken me to far-off and amazing locations everywhere on this great planet. I look back on many excursions in my life and remember the thrill of so many amazing adventures. I first realized the uplifit in perspective and spirit that travel can provide for us all when I was sailing towards Cairo on the deep azure Mediterranean sea. I felt so free!

I love the zestful, alive feelings I get when observing the wondrous Pyramid of the Sun in Teotihuacan, Central Mexico. Or the feeling of starlight dining under the Acropolis in Athens. My tastebuds were awakened forever one afternoon in a small Parisienne cafe. And I will always remember the feeling of the Great Pyramid in Cairo, Egypt against my back as my picture was snapped. So much action and excitement! But I must admit I also love the Caribbean Sea, and kicking my heals back to just relax once in a while! 

My journey took an amazing turn when I started a job with a company in Tokyo Japan. My first days in Tokyo were a bit challenging because I found myself in a modern culture on the other side of the planet, where I could not read, write or communicate with anyone! Luckily, I had three things going for me: a map, my interpreters at work, and my gusto.

Now, looking back at 8 years of journeying to Tokyo, Japan, I know and love this place deeply. I love the innocence here. I love the revitalizing honesty and quietude, and the foods are out of this world!  My experiences in Japan have been highlighted by my personal gratitude to my Japanese friends, who have showed me the insider view of Japan's culture. The streets of Tokyo, with their ultra-modern and old-world combinations, have become a home away from home for me. So, where ever I roam in this beautiful world, under the skylines of many destiantions that await me, I hope to take you along for the journey!    
</div>


<div class="row home-padding">
    
        <div class="about-2 height-image"></div>
        <a href="http://www.totravelandbloom.com/"><h2 class="logo">Click here to learn more about me!</h2></a>    

<div class="home-padding"></div>
Hello! My name is Ellen, co-founder of Skyline Journey :) My first major trip abroad was to Nepal, where I spent 4 months studying abroad...talk about culture shock!! I was so challenged and stretched by the experience, and also flat out amazed by many of the sights and people. I stayed in a remote mountain village, participated in Hindu holidays, and hiked in the Himalayas. Since then, I have not been able to get enough of that specific exhilaration which comes from experiencing new countries & cultures. I collect these experiences like gold.  

My most recent trip abroad was a whirlwind trip throughout Europe, where I visited 10 countries. I road-tripped around Iceland -- stumbling upon rainbows & waterfalls, charming shaggy ponies & wild sheep, and photographing mountain after mountain after mountain. I lounged on numerous hidden beaches of Portugal, tucked between sandstone cliffs and caves. I traipsed through Paris, picnic-ing along the Seine with wine at sunset. A definite highlight was a scenic train ride between Italy & Switzerland, which revealed to me the Matterhorn for the first time -- crowning jewel of the Swiss Alps. 

Japan, however, is surely one of my favorite places I've ever seen. In the heart of Tokyo, even if the bustling sidewalks seem at first chaotic, you quickly sense the order and peace you're surrounded with. You turn corners and find ornate shrines, and stop for tea at interesting cafes. The wonders are endless, within and without Tokyo. Mt. Fuji will captivate you, and you won't be able to stop staring at its beauty. Japan is a bucket-list destination like none other.

A huge passion project of mine is the travel blog I run: To Travel and Bloom (www.totravelandbloom.com). My goal in starting this blog was to hold on to memories, and keep my love for travel in the forefront of my mind. And travel just keeps becoming a bigger and bigger part of my life. 

I am also a travel agent working for Dreamavoo Travel and Tours, a CCRA-accredited agency, affiliated with Travel Planners International. Dreamavoo will be hosting Skyline Journey's premiere Japan trip...and I could not be more excited!!

</div>

&nbsp;

</div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="body-padding"></div>
<div class="row home-padding">
    <div class="center">
        <h1 class="logo">Skyline Journey</h1>
        <p>
        </p>
    </div>
</div>

<div class="row home-padding">
    <div class="col-md-4">
        <div class="about-main height-image zoom"></div>
        
    </div>
    <div class="col-md-8">
    Meet Marjorie & Ellen 😊 They have known each other for almost 10 years, and first traveled abroad together in 2017. 

Marjorie is an extremely experienced world traveler. She has been to Tokyo alone 15 times! She spends a full month there biannually for work. She has brought various friends and family along to Asia, to act as a tour guide & reveal to them the wonders of Japan. 

Ellen & Marjorie spent two weeks in Japan together in 2017. Ellen got to explore Tokyo and Mt. Fuji for the first time, and it was all totally stress-free because of Marjorie’s knowledge & guidance.

Ellen & Marjorie recently realized that together, they could make their dream job happen. Combining Marjorie's extensive experience in Japan & Ellen's work as a travel agent, they decided to launch Skyline Journey.
 
Skyline Journey is a US-based tour company. Marjorie & Ellen are the guides for small group tours, capped at around 20 people. Their goal is to give you a warm, welcoming, personalized, and authentic experience to the best of their ability.
   </div>
    
</div>

<div class="row home-padding">
    
    <div class="col-md-8">
        Hi! I'm Marjorie O'Rourke, co-founder of Skyline Journey. We are a premiere American-based company, specializing in personalized, exclusive, worldwide travel.

I absolutely love to travel. I love waking up in a new location and seeing the amazing adventure before me. I'm also a foodie, so I really enjoy epicurean delights from all over this world.

My wanderlust began when I was a a teen, and has taken me to far-off and amazing locations everywhere on this great planet. I look back on many excursions in my life and remember the thrill of so many amazing adventures. I first realized the uplifit in perspective and spirit that travel can provide for us all when I was sailing towards Cairo on the deep azure Mediterranean sea. I felt so free!

I love the zestful, alive feelings I get when observing the wondrous Pyramid of the Sun in Teotihuacan, Central Mexico. Or the feeling of starlight dining under the Acropolis in Athens. My tastebuds were awakened forever one afternoon in a small Parisienne cafe. And I will always remember the feeling of the Great Pyramid in Cairo, Egypt against my back as my picture was snapped. So much action and excitement! But I must admit I also love the Caribbean Sea, and kicking my heals back to just relax once in a while! 

My journey took an amazing turn when I started a job with a company in Tokyo Japan. My first days in Tokyo were a bit challenging because I found myself in a modern culture on the other side of the planet, where I could not read, write or communicate with anyone! Luckily, I had three things going for me: a map, my interpreters at work, and my gusto.

Now, looking back at 8 years of journeying to Tokyo, Japan, I know and love this place deeply. I love the innocence here. I love the revitalizing honesty and quietude, and the foods are out of this world!  My experiences in Japan have been highlighted by my personal gratitude to my Japanese friends, who have showed me the insider view of Japan's culture. The streets of Tokyo, with their ultra-modern and old-world combinations, have become a home away from home for me. So, where ever I roam in this beautiful world, under the skylines of many destiantions that await me, I hope to take you along for the journey!
    </div>
    <div class="col-md-4">
        <div class="about-1 height-image zoom"></div>
        <a href="http://www.marjorieorourke.com/"><h2 class="logo">Click here to learn more about me!</h2></a>
    </div>
</div>

<div class="row home-padding">
    <div class="col-md-4">
        <div class="about-2 height-image zoom"></div>
        <a href="http://www.totravelandbloom.com/"><h2 class="logo">Click here to learn more about me!</h2></a>
    </div>
    <div class="col-md-8">
    Hello! My name is Ellen, co-founder of Skyline Journey :) My first major trip abroad was to Nepal, where I spent 4 months studying abroad...talk about culture shock!! I was so challenged and stretched by the experience, and also flat out amazed by many of the sights and people. I stayed in a remote mountain village, participated in Hindu holidays, and hiked in the Himalayas. Since then, I have not been able to get enough of that specific exhilaration which comes from experiencing new countries & cultures. I collect these experiences like gold.  

My most recent trip abroad was a whirlwind trip throughout Europe, where I visited 10 countries. I road-tripped around Iceland -- stumbling upon rainbows & waterfalls, charming shaggy ponies & wild sheep, and photographing mountain after mountain after mountain. I lounged on numerous hidden beaches of Portugal, tucked between sandstone cliffs and caves. I traipsed through Paris, picnic-ing along the Seine with wine at sunset. A definite highlight was a scenic train ride between Italy & Switzerland, which revealed to me the Matterhorn for the first time -- crowning jewel of the Swiss Alps. 

Japan, however, is surely one of my favorite places I've ever seen. In the heart of Tokyo, even if the bustling sidewalks seem at first chaotic, you quickly sense the order and peace you're surrounded with. You turn corners and find ornate shrines, and stop for tea at interesting cafes. The wonders are endless, within and without Tokyo. Mt. Fuji will captivate you, and you won't be able to stop staring at its beauty. Japan is a bucket-list destination like none other.

A huge passion project of mine is the travel blog I run: To Travel and Bloom (www.totravelandbloom.com). My goal in starting this blog was to hold on to memories, and keep my love for travel in the forefront of my mind. And travel just keeps becoming a bigger and bigger part of my life. 

I am also a travel agent working for Dreamavoo Travel and Tours, a CCRA-accredited agency, affiliated with Travel Planners International. Dreamavoo will be hosting Skyline Journey's premiere Japan trip...and I could not be more excited!!
    </div>
    
</div>

<div class="bottom-padding-home"></div>

app/views/static_pages/booking.html.erb
<% provide(:title, "Booking") %>
<div class="body-padding"></div>
<div class="row home-padding">
    <div class="center">
        <h1 class="logo">Skyline Journey</h1>
        &nbsp;
        <h2>We invite you to join us on our upcoming trip to Japan in Springtime 2019!</h2> 

        <h3><%= link_to "For trip details click here", info_path %></h3>
        <div class="mobile-padding">
        <p>
            To reserve your space, make a $99 deposit to Dreamavoo Travel & Tours, the travel agency hosting this trip, by clicking the PayPal button.
            <h3><u>We are offering early registration discounts:</u></h3>
   
                <p>$100 Early Registration Discount if you reserve your space before December 1, 2018.</p>
                <p>50 Early Registration Discount if you reserve your space before January 1, 2019.</p>
                <p>Note that this is a premiere small group tour with limited spaces... Reserve your space today!</p>
            
        </p>
   </div>
        &nbsp;
    
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="UTEJ3B7RB67MW">
            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
    </div>
</div>

app/views/static_pages/contact.html+phone.erb
<% provide(:title, "Contact") %>
<div class="body-padding"></div>
<div class="row home-padding">
    <div class="center mobile-padding">
        <h1 class="logo">Skyline Journey</h1>
        &nbsp;
        <iframe style="z-index: 2 !important" src="https://docs.google.com/forms/d/e/1FAIpQLSeSF3ThRYkBMcl7w_4x5A5oHu7ivOZa_RGdv4MXvZQ2tL-ZSQ/viewform?embedded=true" width="100%" height="1015" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
    </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="body-padding"></div>
<div class="row home-padding">
    <div class="center">
        <h1 class="logo">Skyline Journey</h1>
        &nbsp;
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeSF3ThRYkBMcl7w_4x5A5oHu7ivOZa_RGdv4MXvZQ2tL-ZSQ/viewform?embedded=true" width="640" height="1015" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
    </div>
</div>

app/views/static_pages/home.html+phone.erb
<% provide(:title, "Home") %>
<% provide(:title, "Home") %>
<div class="body-padding"></div>
<div class="mobile-padding">
    
<div class="row home-padding">
    <div class="center">
        <h1 class="logo">Skyline Journey</h1>
        <p class="center logo home-padding">Small Group Tours</p>
    </div>
</div>

<div class="row home-padding">

        <div class="background-gif height-image center">
            <div class="logo-image mobile-z">
                
        </div>
</div>

<div class="home-padding">
    <a href="/trip1">
    <div class="background-gif-1 height-image">
            
                <h1 class="center logo mobile-links">Tokyo Spring Cherry Blossom Tours 2019</h1>
                <p class="left logo mobile-links">Tokyo</p>
                <p class="left logo mobile-links">Hakone</p>
                <p class="left logo mobile-links">Mt. Fuji</p>
                <p class="left logo mobile-links">Kyoto</p>
    
        </div>
    </a>
</div>

<div class="home-padding">
    <a href="/trip2">
        <div class="background-gif-6 height-image">
           
                <h1 class="center logo mobile-links">Summer Mt. Fuji Tour 2019</h1>
                <p class="left logo mobile-links">Mt. Fuji</p>
                <p class="left logo mobile-links">Tokyo</p>
                <p class="left logo mobile-links">Okinawa</p>
                <p class="left logo mobile-links">Japan's Southern Islands</p>
            
        </div>
    </a>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="body-padding"></div>
<h1 class="center logo">Skyline Journey</h1>
<p class="center logo home-padding">Small Group Tours</p>
<div class="row home-padding">
    <div class="col-md-8">
        <div class="background-gif-1 height-image zoom">
            <div class="logo-text">
                <h1 class="left logo">Tokyo Spring Cherry Blossom Tours 2019</h1>
                <p class="left logo">Tokyo</p>
                <p class="left logo">Hakone</p>
                <p class="left logo">Mt. Fuji</p>
                <p class="left logo">Kyoto</p>
            </div>
             <div>
                <a href="/trip1" role="button">Learn more!</a>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="background-gif-2 height-image zoom">
            <div>
                <a href="/contact" role="button">Contact Us!</a>
            </div>
        </div>
    </div>
</div>

<div class="row home-padding">
    <div class="col-md-4">
        <div class="background-gif-3 height-image zoom">
            
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="background-gif height-image">
            <div class="logo-image">
                
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="background-gif-4 height-image zoom">
            
        </div>
    </div>
</div>

<div class="row home-padding">
    <div class="col-md-4">
        <div class="background-gif-5 height-image zoom">
            <div>
                <a href="/about" role="button">About Skyline Tours</a>
            </div>
        </div>
    </div>
    
    <div class="col-md-8">
        <div class="background-gif-6 height-image zoom">
            <div class="logo-text">
                <h1 class="left logo">Summer Mt. Fuji Tour 2019</h1>
                <p class="left logo">Mt. Fuji</p>
                <p class="left logo">Tokyo</p>
                <p class="left logo">Okinawa</p>
                <p class="left logo">Japan's Southern Islands</p>
            </div>
             <div>
                <a href="/trip2" role="button">Learn more!</a>
            </div>
        </div>
    </div>
</div>
<div class="bottom-padding-home"></div>

app/views/static_pages/info.html.erb
<div class="body-padding"></div>
<div class="row home-padding">
    <div class="center">
        <h1 class="logo">Skyline Journey</h1>
    </div>
</div>
<div class="center">
We invite you to join us on our upcoming trip to Japan in March 2019! Read on for more important info.



$100 Early Registration Discount if you reserve your space before December 1, 2018

$50 Early Registration Discount if you reserve your space before January 1, 2019

 

Note that this is a premiere small group tour with limited spaces, capped at 22 travelers. Reserve your space today! We can't wait to travel the world with you!

&nbsp;

<h1 class="logo">Trip dates:</h1> 
</div>
<ul>
<li>Arrive in Haneda Airport (HND), Tokyo on Saturday March 23, 2019. This means you will likely need to begin your journey on Friday March 22 -- it takes a long time to fly to the other side of the world! Tokyo's timezone is also ahead of Eastern Standard Time by 13 hours (14 hours after daylight savings), so you "lose" that time.</li>
<li>Depart Kansai International Airport (KIX), near Kyoto on Wednesday April 3, 2019. Again, this means you will spend likely a full 24 hours traveling, but you do "gain back" the time from the timezone changes.</li> 
<li>Airfare is not included in the tour package, but we would be happy to help you arrange the best airfare for you.</li>
<li>We will do our best to meet you at the Haneda Airport and escort you to the hotel. Please either organize your air travel through us, or inform us of your arrival and departure times. We will also travel as a group from Kyoto to the Kansai International Airport at the end of the trip.</li>
</ul>
 

<h2 class="logo center">Inclusions:</h2>
<ul>
<li>All accommodations</li>
    <ul>
     <li>5 nights Western-style hotel room in Tokyo</li>
     <li>6 nights Japanese-style ryokans in Hakone, Kawaguchiko, & Kyoto</li>
     <li>Accommodations are available at 2 different price points: high-end (primarily 4*) or budget (primarily 3*)</li>
    </ul>
<li>All breakfasts</li>
<li>3 dinners</li>
<li>Transportation between cities, and most transportation around cities</li>
<li>Luggage forwarding between cities</li>
<li>Admissions & activities described in itinerary (Everything from ascending Tokyo Tower to experiencing a robot cafe to soaking in green tea baths!)</li>
<li>Two friendly, full-service tour guides that speak English, will help you every step of the way, and can't wait to share the Japan that they know & love</li> with you 
<li>Thorough informational pre-departure packet, filled with info about cultural norms, what to expect, how to pack, and so much more</li>
</ul>
 

<h2 class="logo center">Exclusions:</h2>
<ul>
<li>International flights, although we can help you arrange the best airfare for you</li>
<li>Travel insurance, although this is strongly recommended, and we can help you secure the best plan for you</li>
<li>Additional dinners & lunches</li>
<li>Alcoholic beverages</li>
<li>Some transportation within Tokyo, such as daily subway rides to activities</li>
<li>Personal expenses such as shopping, telephone, and laundry</li>
</ul>
 

<h2 class="logo center">Activity Level:</h2>
<ul>
<li>This active tour will allow you to experience Japan in an intimate and exciting way...you won't be stuck on a tour bus! You should expect to spend part of each day touring on foot. This will allow you to come face-to-face with the Wonders of Japan!</li>
</ul>

 

<h2 class="logo center">Pricing:</h2>
<ul>
<li>Starting from $4,884, based on double occupancy room (Inquire about single rooming and supplements)</li>
<li>There are two available levels of accommodation: high-end (primarily 4*) and budget (primarily 3*). This is in order to make the trip accessible to a wide range of travelers. Both levels of hotels are directly nearby each other, and all other aspects of the trip remain the same, so that we will remain one cohesive group.</li>
<li>$100 Early Registration Discount if you reserve your space before December 1, 2018</li>
<li>$50 Early Registration Discount if you reserve your space before January 1, 2019</li>
<li>$99 deposit to reserve your space</li>   
<li>One third of remaining balance (after $99 deposit) due within one month of deposit date</li>
<li>Full remaining balance due at least 40 days before trip departure</li>
</ul>
 

<h2 class="logo center">Additional Information:</h2>
<ul>
<li>We will do our best to accommodate dietary restrictions. Note that Japanese meals are heavily centered on seafood, rice, and noodles. However, Ellen is a vegetarian and has successfully been able to maintain her diet in Japan. Please let us know about special meal restrictions.</li>
<li>This personalized journey is truly a once-in-a-lifetime experience. We could not be more thrilled that you are ready to encounter all of Japan's wonders and magic alongside us!</li>
<li>**By making a $99 deposit, visitors understand that this is a non-refundable deposit toward their trip, and the only way to reserve their space.</li>
</ul>
<div class="bottom-padding-home"></div>

app/views/static_pages/trip2.html.erb
<div class="body-padding"></div>
<div class="row home-padding">
    <div class="center">
        <h1 class="logo">Skyline Journey</h1>
        <h1 class="logo">Summer Mt. Fuji Tour 2019</h1>
        &nbsp;
        <h1 class="logo">The trip will include:</h1>
            <h2>Tokyo</h2>
            <h2>Mt. Fuji Sunrise Climb</h2>
            <h2>Japan's Southern Islands</h2>
        <h1 class="logo">More info coming soon!</h1>
    </div>
</div>